// Errors
sin=33 
sin(2)=2 
myudf=2 // define myudf before testing this
x(3)=99
x(4~5)=noise(1)
nd.arr(3)=99
nd.arr(4~5)=noise(1)
c{5}(3)=99
c{5}(4~5)=noise(1)
// END OF Errors

xx=1:2:20
xx(3)=999
xx([2 5 9]) = 1
xx([2 5 9]) = -1:-3
xx(1:3)=[]
xx(3:4) = 3:5 // error
xx(3) = "string" //error
xx(100) = 1 // error
xx(4~7) = noise(1) // error

yy=tone(500,1000)
yy(1:444)=0 // FAIL -- 
yy(1:444)=1:444 // error
yy(0~500)=silence(500)
yy.dur
yy.rms
yy(500~1000)=[]
yy.dur
yy.rms

c={1:2:20, "bjkwon", noise(1000), 88}
c{4} = sqrt(2:7)
c{4}(5)=999
c{4}([2 5 6]) = 1
c{4}(1:3)=[]
c{4}(6:7) = 3:5 // error

nd.sq = sqrt(2:8)
nd.sq(5)=999;
nd.sq([2 5 6]) = 1;
nd.sq(1:3)=[];
nd.sq(6:7) = 3:5; // error

mm.prop1.arr=1:2:20
mm.prop1.prop2.prop3 = "bjk"
md.prop1.prop2.prop3 = "bjk";
md.prop1.arr=1:2:20;
md.prop1.arr(3:4)= -1

===========================================================
Test at 12:54 AM 9/12/2022
PASS except the following---
myudf=2 
--> There was a udf called temp1.aux 
    temp returned 4, but
    temp = 2 treated temp as a variable and a new var was created, then
    temp + 2 crashed the application
yy(1:444)=0
--> this should be acceptable, but issued this "Error: LHS and RHS have different object type."
=========================================================
5:21 PM 9/12/2022
Undetected error found.

p.val=200 --> OK
p.name="str" --> This erases the existing p.val

Fixed. 6:39 PM 9/12/2022
committed again
==============================================================

